name: fitbitter
description: A Flutter package to make your life easier when dealing with Fitbit APIs.
version: 1.1.1
homepage: https://github.com/gcappon/fitbitter
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_auth: #used to implement oauth 2.0
    git:
      url: https://github.com/noga-dev/flutter_web_auth.git
  dio: ^4.0.6 #better web browser
  logger: ^1.0.0
  intl: ^0.17.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
